const tags = [
  'monilukutaito',
  'kielten rikas maailma',
  'tieto-ja viestintäteknologia',
  'arjen taidot',
  'vuorovaikutus',
  'leikillinen pedagogiikka',
  'luontokasvatus',
  'koodaus',
  'ilmaisu',
  'arviointi',
  'tunteet',
  'tarinankerronta',
  'osallisuus',
  'pedagoginen dokumentointi',
  'kamerakynän pedagogiikka',
  'thinglink',
  'padlet',
  'adobe spark',
  'minecraft',
  'book creator',
  'chatter pix',
  'google tour creator',
  'qr-koodi',
  'bee-bot',
  'video',
  'ääni',
  'kuva',
  'teksti',
  'piirros',
  'animaatio',
  'vr',
  'ar',
  'alle 3-vuotiaat',
  'yli 3-vuotiaat',
  'esiopetus',
  'alkuopetus',
  'varhaiskasvatus'
]

// export { tags }
module.exports = { tags }
